import { StyleSheet } from "react-native";
import { AppColors as Colors } from "../../utils/theme";
import { FONTS } from "../../utils/FONTS";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  background: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 16,
    paddingBottom: 36,
    gap: 16,
  },
  introCard: {
    backgroundColor: Colors.primaryopacity,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 4,
  },
  introTitle: {
    fontSize: 16,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  introText: {
    fontSize: 13,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    lineHeight: 19,
  },
  typeCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  typeCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  typeIconBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  typeIcon: {
    width: 22,
    height: 22,
  },
  typeTexts: {
    flex: 1,
    gap: 3,
  },
  typeTitle: {
    fontSize: 15,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  typeSubtitle: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  rightIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.darkText,
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    gap: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  sectionMeta: {
    fontSize: 12,
    fontFamily: FONTS.Medium,
    color: Colors.primary,
    backgroundColor: Colors.primarylite,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  sectionHint: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    lineHeight: 18,
    marginTop: -4,
  },
  photoRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  photoColumn: {
    flex: 1,
    gap: 8,
  },
  slotCaption: {
    fontSize: 13,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  photoSlot: {
    width: "100%",
    aspectRatio: 0.78,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#D5DCE5",
    borderStyle: "dashed",
    backgroundColor: "#F7F9FC",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  photoSlotFilled: {
    borderStyle: "solid",
    borderColor: Colors.primary,
    backgroundColor: Colors.white,
  },
  photoSlotError: {
    borderColor: "#E85A5A",
    borderStyle: "dashed",
    backgroundColor: "#FFF8F8",
  },
  fieldError: {
    fontSize: 12,
    color: "#D64545",
    fontFamily: FONTS.Regular,
    lineHeight: 16,
  },
  dateFieldError: {
    borderColor: "#E85A5A",
    backgroundColor: "#FFF8F8",
  },
  photoPreview: {
    width: "100%",
    height: "100%",
  },
  photoOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 10,
    backgroundColor: "rgba(0,0,0,0.12)",
  },
  photoPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: 12,
  },
  photoIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.lightprimary1,
    alignItems: "center",
    justifyContent: "center",
  },
  photoIconCircleError: {
    borderColor: "#F0BABA",
    backgroundColor: "#FFF5F5",
  },
  photoPlaceholderIcon: {
    width: 24,
    height: 24,
  },
  photoLabel: {
    fontSize: 13,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
    textAlign: "center",
  },
  photoAction: {
    fontSize: 12,
    fontFamily: FONTS.Medium,
    color: Colors.darkText,
    textAlign: "center",
  },
  photoActionError: {
    color: "#D64545",
  },
  retakeBtn: {
    backgroundColor: "rgba(0,0,0,0.62)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
  },
  retakeText: {
    fontSize: 12,
    fontFamily: FONTS.SemiBold,
    color: Colors.white,
  },
  field: {
    gap: 8,
  },
  label: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  required: {
    color: "#D64545",
  },
  dateField: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1.2,
    paddingHorizontal: 14,
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    backgroundColor: Colors.white,
    borderColor: "#D5DCE5",
  },
  dateFieldActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryopacity,
  },
  dateIcon: {
    width: 22,
    height: 22,
  },
  dateText: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.black,
  },
  datePlaceholder: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  error: {
    fontSize: 13,
    color: Colors.red,
    fontFamily: FONTS.Regular,
  },
  docCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    gap: 4,
  },
  docCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  docCardTexts: {
    flex: 1,
    gap: 4,
  },
  docTitle: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  docMeta: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  emptyText: {
    fontSize: 13,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    textAlign: "center",
    paddingVertical: 8,
  },
  retryBtn: {
    alignSelf: "center",
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 7,
    backgroundColor: Colors.primary,
  },
  retryBtnText: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.white,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.55)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
});
