export const Images = {
  addImage: require("../assets/addImage.png"),
  arrow: require("../assets/arrow.png"),
  back: require("../assets/back.png"),
  bank: require("../assets/bank.png"),
  brand: require("../assets/brand.png"),
  camera: require("../assets/camera.png"),
  close: require("../assets/close.png"),
  company: require("../assets/company.png"),
  connection: require("../assets/connections.png"),
  date: require("../assets/date.png"),
  document: require("../assets/document.png"),
  dots: require("../assets/dots.png"),
  down: require("../assets/down.png"),
  downArrow: require("../assets/downArrow.png"),
  edit: require("../assets/edit.png"),
  eye: require("../assets/eye.png"),
  eyeoff: require("../assets/eye-off.png"),
  facebook: require("../assets/facebook.png"),
  filter: require("../assets/filter.png"),
  gallery: require("../assets/gallery.png"),
  home: require("../assets/home.png"),
  linkdin: require("../assets/linkdin.png"),
  location: require("../assets/location.png"),
  lock: require("../assets/lock.png"),
  logo: require("../assets/logo.png"),
  roxar: require("../assets/roxar.png"),
  logout: require("../assets/logout.png"),
  mail: require("../assets/mail.png"),
  Modal: require("../assets/modal.png"),
  name: require("../assets/name.png"),
  nationality: require("../assets/nationality.png"),
  noconnection: require("../assets/noconnection.png"),
  number: require("../assets/number.png"),
  one: require("../assets/1.png"),
  phone: require("../assets/phone.png"),
  plus: require("../assets/plus.png"),
  profile: require("../assets/profile.png"),
  projectname: require("../assets/projectname.png"),
  refresh: require("../assets/refresh.png"),
  roundlogo: require("../assets/roundlogo.webp"),
  search: require("../assets/search.png"),
  splash: require("../assets/splash.png"),
  star: require("../assets/star.png"),
  status: require("../assets/status.png"),
  stuts: require("../assets/stuts.png"),
  time: require("../assets/time.png"),
  user: require("../assets/user.png"),
  userblanck: require("../assets/userblanck.png"),
  website: require("../assets/website.png"),
  wp: require("../assets/wp.png"),
  delete: require("../assets/delete.png"),
  clock: require("../assets/clock.png"),
  net: require("../assets/net.png"),
  menu: require("../assets/menu.png"),
  documentlogo: require("../assets/documentlogo.png"),
  pdflogo: require("../assets/pdflogo.png"),
  plen: require("../assets/plen.png"),
  arrivels: require("../assets/arrivels.png"),
  dapartuar: require("../assets/dapartuar.png"),
  taxi: require("../assets/taxi.png"),
  locationdot: require("../assets/locationdot.png"),
  flag: require("../assets/flag.png"),
  OffFlash: require("../assets/OffFlash.png"),
  OnFlash: require("../assets/OnFlash.png"),
  Success: require("../assets/Success.png"),
  WrongIcon: require("../assets/WrongIcon.png"),
  Info: require("../assets/Info.png"),
  defaultImage: require("../assets/defaultImage.jpeg"),
  trash: require("../assets/trash.png"),
    pause: require("../assets/pause.png"),
  check: require("../assets/check.png"),
  ScannerCenter: require("../assets/ScannerCenter.png"),
  EventAnimation: require("../assets/success.json"),
  Faild: require("../assets/Failed.json"),


};

// export const Images = {
//   logo: require("../assets/logo.png"),
//   mail: require("../assets/mail.png"),
//   lock: require("../assets/lock.png"),
//   eye: require("../assets/eye.png"),
//   eyeoff: require("../assets/eye-off.png"),
//   search: require("../assets/search.png"),
//   filter: require("../assets/filter.png"),
//   user: require("../assets/user.png"),
//   time: require("../assets/time.png"),
//   down: require("../assets/down.png"),
//   home: require("../assets/home.png"),
//   profile: require("../assets/profile.png"),
//   logout: require("../assets/logout.png"),
//   back: require("../assets/back.png"),
//   splash: require("../assets/splash.png"),
//   refresh: require("../assets/refresh.png"),
//   close: require("../assets/close.png"),
//   company: require("../assets/company.png"),
//   arrow: require("../assets/arrow.png"),
//   downArrow: require("../assets/downArrow.png"),
//   addImage: require("../assets/addImage.png"),
//   name: require("../assets/name.png"),
//   location: require("../assets/location.png"),
//   one: require("../assets/1.png"),
//   date: require("../assets/date.png"),
//   bank: require("../assets/bank.png"),
//   document: require("../assets/document.png"),
//   facebook: require("../assets/facebook.png"),
//   linkdin: require("../assets/linkdin.png"),
//   wp: require("../assets/wp.png"),
//   edit: require("../assets/edit.png"),
//   userblanck: require("../assets/userblanck.png"),
//   roundlogo: require("../assets/roundlogo.webp"),
//   nationality: require("../assets/nationality.png"),
//   dots: require("../assets/dots.png"),
//   camera: require("../assets/camera.png"),
//   gallery: require("../assets/gallery.png"),
//   phone: require("../assets/phone.png"),
//   stuts: require("../assets/stuts.png"),
//   Modal: require("../assets/modal.png"),
//   brand: require("../assets/brand.png"),
//   licence: require("../assets/licence.png"),
//   projectname: require("../assets/projectname.png"),
//   website: require("../assets/website.png"),
//   number: require("../assets/number.png"),
//   status: require("../assets/status.png"),
//   connection: require("../assets/connections.png"),
//   noconnection: require("../assets/noconnection.png"),
//   star: require("../assets/star.png"),
//   plus: require("../assets/plus.png"),
// };
